---
- name: Setup Workstation
  hosts: localhost
  connection: local
  roles:
  - name: common-packages
    tags: common-packages
  - name: geerlingguy.docker
    tags: docker
    become: true
    vars:
      docker_users:
        - "{{ ansible_user_id }}"
  - name: gantsign.oh-my-zsh
    vars:
      oh_my_zsh_plugins:
        - git
        - zsh-completions
      users:
        - username: "{{ ansible_user_id }}"
  - name: zsh
    tags: zsh
  - name: apps
    tags: apps
  - name: devel
    tags: devel
