---
- name: Setup Workstation
  hosts: localhost
  connection: local
  roles:
  - name: packages
    tags: packages
  - name: geerlingguy.docker
    tags: docker
    become: true
    vars:
      docker_users:
        - "{{ ansible_user_id }}"
  - name: snaps
    tags: snaps
  - name: code
    tags: code
  - name: zsh
    tags: zsh
