---
snaps:
  - name: chromium

  - name: code

  - name: gitkraken
    classic: yes

  - name: go
    classic: yes

  - name: inkscape
    classic: yes

  - name: keepassxc

  - name: kubectl
    classic: yes

  - name: simplenote
  
  - name: vlc